### ISSUE TITLE
option 5 fails

### ISSUE THREAD

**Issue by TolisTerra** [3rg1s/Inventory#1]
On option 5 when you write how many times you want an item this message appears  : 
Traceback (most recent call last):
  File "inventory.py", line 108, in <module>
    multiple(item_value, times)
  File "inventory.py", line 80, in multiple
    for i in range(times):
TypeError: 'str' object cannot be interpreted as an integer

**Comment by 3rg1s** [comment]
Hello @TolisTerra, issue is resolved. Thank you for raising it. Closing this issue now.
